-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.expired_tokens
(
    token text COLLATE pg_catalog."default" NOT NULL
);

CREATE TABLE IF NOT EXISTS public.parse_requests
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    export_type character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT parse_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);
END;